[package]
name = "DonationPlatform"
version = "0.1.0"

[addresses]
DonationPlatform = "0x1"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'